version: '3.4'

services:
  redis:
    restart: 'no'
    image: redislabs/redisearch:latest
    command: --loglevel verbose

  redis-cli:
    restart: 'no'
    image: redislabs/redisearch:latest
    depends_on:
      - redis
    command: >
      sh -c 'redis-cli -h redis '

  mongo:
    restart: 'no'
    image: mongo:latest
    volumes:
      - ./mongo/data:/data/db

  mongo-cli:
    restart: 'no'
    image: mongo:latest
    depends_on:
      - mongo
    command: >
      sh -c 'mongo --host mongo '

  mongo-express:
    restart: 'no'
    image: mongo-express
    ports:
      - 8082:8081
    depends_on:
      - mongo
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "mongo:27017", "--", "/docker-entrypoint.sh"]

  readis:
    restart: 'no'
    image: hollodotme/readis
    ports:
      - 8080:80
    volumes:
      - ./config:/code/config:ro
    depends_on:
      - redis

  phpredisadmin:
    restart: 'no'
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    ports:
      - 8081:80
